language: python

python:
  - "3.6"

dist: xenial

services:
  - xvfb

install:
  - python3 setup.py

env:
  # avoid ALSA errors for audio
  - AUDIODEV=null


script:
  - python3 src/test_suite.py
  - mypy src/bearly_dancing.py
  